import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

import {
  materialRenderers,
  materialCells,
} from "@jsonforms/material-renderers";

import { JsonForms } from "@jsonforms/react";

const schema = {
  type: "object",
  properties: {
    name: {
      type: "string",
      minLength: 3,
      description: "Please enter your name",
    },
    vegetarian: {
      type: "boolean",
    },
    birthDate: {
      type: "string",
      format: "date",
    },
    nationality: {
      type: "string",
      enum: ["DE", "IT", "JP", "US", "RU", "Other"],
    },
    personalData: {
      type: "object",
      properties: {
        age: {
          type: "integer",
          description: "Please enter your age.",
        },
        height: {
          type: "number",
        },
        drivingSkill: {
          type: "number",
          maximum: 10,
          minimum: 1,
          default: 7,
        },
      },
      required: ["age", "height"],
    },
    occupation: {
      type: "string",
    },
    postalCode: {
      type: "string",
      maxLength: 5,
    },
  },
  required: ["occupation", "nationality"],
};

const uischema = {
  type: "VerticalLayout",
  elements: [
    {
      type: "HorizontalLayout",
      elements: [
        {
          type: "Control",
          scope: "#/properties/name",
        },
        {
          type: "Control",
          scope: "#/properties/personalData/properties/age",
        },
        {
          type: "Control",
          scope: "#/properties/birthDate",
        },
      ],
    },
    {
      type: "Label",
      text: "Additional Information",
    },
    {
      type: "HorizontalLayout",
      elements: [
        {
          type: "Control",
          scope: "#/properties/personalData/properties/height",
        },
        {
          type: "Control",
          scope: "#/properties/nationality",
        },
        {
          type: "Control",
          scope: "#/properties/occupation",
          suggestion: [
            "Accountant",
            "Engineer",
            "Freelancer",
            "Journalism",
            "Physician",
            "Student",
            "Teacher",
            "Other",
          ],
        },
      ],
    },
  ],
};

const initialData = {
  name: "John Doe",
  vegetarian: false,
  birthDate: "1985-06-02",
  personalData: {
    age: 34,
  },
  postalCode: "12345",
};

export default function Forms() {
  const [data, setData] = useState(initialData);
  // return <div className="App"></div>;
  return (
    <>
      <Head>
        <title>Encryption example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          position: "absolute",
          top: "100px",
          left: "200px",
          width: "60%",
        }}
      >
        <h1>Encryption example</h1>
        <div>
          <JsonForms
            schema={schema}
            uischema={uischema}
            data={data}
            renderers={materialRenderers}
            cells={materialCells}
            onChange={({ data, errors }) => setData(data)}
          />
        </div>
        <button
          onClick={() => {
            doSomething();
          }}
        >
          Import PEM
        </button>
      </main>

      <footer className={styles.footer}></footer>
    </>
  );
}
